# ==============================================================================
# KUBU CORE DAEMON CONFIGURATION FILE (kubu.conf)
# ==============================================================================

daemon=1
listen=1
port=33874
bind=0.0.0.0
maxconnections=125

server=1
rpcport=33873
rpcbind=127.0.0.1
rpcallowip=127.0.0.1/32
rpcthreads=16
rpcclienttimeout=900

rpcuser=kubu_rpc_admin
rpcpassword=ChangeThisToAStrongUnguessablePassword33873!

txindex=1
prune=0

dbcache=1024
maxmempool=300

logtimestamps=1
debug=0
shrinkdebugfile=1
