# 1. Create user man directory
mkdir -p ~/.local/share/man/man1

# 2. Save the content to the file
cat << 'EOF' > ~/.local/share/man/man1/kubu-cli.1
.\" DO NOT MODIFY THIS FILE!  It was generated by help2man 1.47.13.
.TH KUBU-CLI "1" "December 2024" "kubu-cli v1.1.0.0" "User Commands"
.SH NAME
kubu-cli \- manual page for kubu-cli v1.1.0.0
.SH DESCRIPTION
Kubu Core RPC client version v1.1.0.0
.SS "Usage:"
.TP
kubu\-cli [options] <command> [params]
Send command to Kubu Core
.IP
kubu\-cli [options] \fB\-named\fR <command> [name=value] ... Send command to Kubu Core (with named arguments)
kubu\-cli [options] help                List commands
kubu\-cli [options] help <command>      Get help for a command
.SH OPTIONS
.HP
\-?
.IP
This help message
.HP
\fB\-conf=\fR<file>
.IP
Specify configuration file (default: kubu.conf)
.HP
\fB\-datadir=\fR<dir>
.IP
Specify data directory
.HP
\fB\-backupdir=\fR<dir>
.IP
Specify directory where to write backups and data dumps (default
datadir/backups)
.PP
Chain selection options:
.HP
\fB\-testnet\fR
.IP
Use the test chain
.HP
\fB\-regtest\fR
.IP
Enter regression test mode, which uses a special chain in which blocks
can be solved instantly. This is intended for regression testing
tools and app development.
.HP
\fB\-named\fR
.IP
Pass named instead of positional arguments (default: false)
.HP
\fB\-rpcconnect=\fR<ip>
.IP
Send commands to node running on <ip> (default: 127.0.0.1)
.HP
\fB\-rpcport=\fR<port>
.IP
Connect to JSON\-RPC on <port> (default: 33873 or testnet: 44873)
.HP
\fB\-rpcwait\fR
.IP
Wait for RPC server to start
.HP
\fB\-rpcuser=\fR<user>
.IP
Username for JSON\-RPC connections
.HP
\fB\-rpcpassword=\fR<pw>
.IP
Password for JSON\-RPC connections
.HP
\fB\-rpcclienttimeout=\fR<n>
.IP
Timeout during HTTP requests (default: 900)
.HP
\fB\-stdin\fR
.IP
Read extra arguments from standard input, one per line until EOF/Ctrl\-D
(recommended for sensitive information such as passphrases)
.SH COPYRIGHT
Copyright (C) 2013-2024 The Bitcoin Core, Dogecoin Core, and Kubu Core
developers

Please contribute if you find Kubu Core useful. Visit
<https://kubucoin.org> for further information about the software.
The source code is available from <https://github.com/kubucoindev/kubu>.

This is experimental software.
Distributed under the MIT software license, see the accompanying file COPYING
or <https://opensource.org/licenses/MIT>

This product includes software developed by the OpenSSL Project for use in the
OpenSSL Toolkit <https://www.openssl.org> and cryptographic software written by
Eric Young and UPnP software written by Thomas Bernard. Paper wallet art
provided by Anacoluthia.
EOF

# 3. View the user-level manual page
man -M ~/.local/share/man kubu-cli
